CREATE TABLE AGRM_OF_PERS_DATA_PROC 
(
  ID NUMBER(19, 0) NOT NULL,
  JCR_UID VARCHAR2(255),
  PERSON_ID NUMBER(19, 0) NOT NULL,
  CONSTRAINT AGRM_OF_PERS_DATA_PROC_PK PRIMARY KEY (ID)
  ENABLE 
);

ALTER TABLE AGRM_OF_PERS_DATA_PROC
ADD CONSTRAINT AGRM_OF_PERS_DATA_PROC_FK1 FOREIGN KEY (PERSON_ID)
REFERENCES PERSON (ID)
ENABLE;

INSERT INTO AGRM_OF_PERS_DATA_PROC (ID, JCR_UID, PERSON_ID) SELECT hibernate_sequence.nextval, APP_AGREEM_UID, ID FROM PERSON;

ALTER TABLE PERSON_AUD DROP COLUMN APP_AGREEM_UID;
ALTER TABLE PERSON DROP COLUMN APP_AGREEM_UID;