CREATE TABLE GOSSRVC_SERV_DOC_TREE_NPA_REF
(
  GOSSRVC_SERVICE_DOC_TREE_ID bigint NOT NULL,
  METHOD_MATERIAL_ID bigint NOT NULL,
  CONSTRAINT GOSSRVC_SERV_DOC_TREE_NPA_PK PRIMARY KEY (GOSSRVC_SERVICE_DOC_TREE_ID, METHOD_MATERIAL_ID)
);


ALTER TABLE GOSSRVC_SERV_DOC_TREE_NPA_REF
  ADD FOREIGN KEY (gossrvc_service_doc_tree_id) REFERENCES gossrvc_service_doc_tree (id)
   ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE GOSSRVC_SERV_DOC_TREE_NPA_REF
  ADD FOREIGN KEY (METHOD_MATERIAL_ID) REFERENCES METHOD_MATERIAL (id)
   ON UPDATE NO ACTION ON DELETE NO ACTION;
