CREATE TABLE GOSSRVC_SERV_DOC_TREE_NPA_REF
(
  GOSSRVC_SERVICE_DOC_TREE_ID NUMBER(19, 0) NOT NULL,
  METHOD_MATERIAL_ID NUMBER(19, 0) NOT NULL,
  CONSTRAINT GOSSRVC_SERV_DOC_TREE_NPA_PK PRIMARY KEY (GOSSRVC_SERVICE_DOC_TREE_ID, METHOD_MATERIAL_ID)
  ENABLE
);

ALTER TABLE GOSSRVC_SERV_DOC_TREE_NPA_REF
ADD CONSTRAINT GOSSRVC_SERV_DOC_TREE_NPA_FK1 FOREIGN KEY (GOSSRVC_SERVICE_DOC_TREE_ID)
REFERENCES gossrvc_service_doc_tree (ID)
ENABLE;

ALTER TABLE GOSSRVC_SERV_DOC_TREE_NPA_REF
ADD CONSTRAINT GOSSRVC_SERV_DOC_TREE_NPA_FK2 FOREIGN KEY (METHOD_MATERIAL_ID)
REFERENCES METHOD_MATERIAL (ID)
ENABLE;


