ALTER SEQUENCE g_bpms_activity_variable_hist INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_activity INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_activity_variable INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_and_join_entry INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_assignment INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_deadline INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_global_data INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_participant_map INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_process INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_process_mgr INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_process_variable INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_resource INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_xpdl INCREMENT BY 50;
ALTER SEQUENCE gen_hist_activity_variable INCREMENT BY 50;
ALTER SEQUENCE hibernate_sequence INCREMENT BY 50;

select nextval('g_bpms_activity_variable_hist');
select nextval('gen_bpms_activity');
select nextval('gen_bpms_activity_variable');
select nextval('gen_bpms_and_join_entry');
select nextval('gen_bpms_assignment');
select nextval('gen_bpms_deadline');
select nextval('gen_bpms_global_data');
select nextval('gen_bpms_participant_map');
select nextval('gen_bpms_process');
select nextval('gen_bpms_process_mgr');
select nextval('gen_bpms_process_variable');
select nextval('gen_bpms_resource');
select nextval('gen_bpms_xpdl');
select nextval('gen_hist_activity_variable');
select nextval('hibernate_sequence');

select nextval('g_bpms_activity_variable_hist');
select nextval('gen_bpms_activity');
select nextval('gen_bpms_activity_variable');
select nextval('gen_bpms_and_join_entry');
select nextval('gen_bpms_assignment');
select nextval('gen_bpms_deadline');
select nextval('gen_bpms_global_data');
select nextval('gen_bpms_participant_map');
select nextval('gen_bpms_process');
select nextval('gen_bpms_process_mgr');
select nextval('gen_bpms_process_variable');
select nextval('gen_bpms_resource');
select nextval('gen_bpms_xpdl');
select nextval('gen_hist_activity_variable');
select nextval('hibernate_sequence');