ALTER SEQUENCE g_bpms_activity_variable_hist INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_activity INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_activity_variable INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_and_join_entry INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_assignment INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_deadline INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_global_data INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_participant_map INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_process INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_process_mgr INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_process_variable INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_resource INCREMENT BY 50;
ALTER SEQUENCE gen_bpms_xpdl INCREMENT BY 50;
ALTER SEQUENCE gen_hist_activity_variable INCREMENT BY 50;
ALTER SEQUENCE hibernate_sequence INCREMENT BY 50;

select g_bpms_activity_variable_hist.nextval from dual;
select gen_bpms_activity.nextval from dual;
select gen_bpms_activity_variable.nextval from dual;
select gen_bpms_and_join_entry.nextval from dual;
select gen_bpms_assignment.nextval from dual;
select gen_bpms_deadline.nextval from dual;
select gen_bpms_global_data.nextval from dual;
select gen_bpms_participant_map.nextval from dual;
select gen_bpms_process.nextval from dual;
select gen_bpms_process_mgr.nextval from dual;
select gen_bpms_process_variable.nextval from dual;
select gen_bpms_resource.nextval from dual;
select gen_bpms_xpdl.nextval from dual;
select gen_hist_activity_variable.nextval from dual;
select hibernate_sequence.nextval from dual;

select g_bpms_activity_variable_hist.nextval from dual;
select gen_bpms_activity.nextval from dual;
select gen_bpms_activity_variable.nextval from dual;
select gen_bpms_and_join_entry.nextval from dual;
select gen_bpms_assignment.nextval from dual;
select gen_bpms_deadline.nextval from dual;
select gen_bpms_global_data.nextval from dual;
select gen_bpms_participant_map.nextval from dual;
select gen_bpms_process.nextval from dual;
select gen_bpms_process_mgr.nextval from dual;
select gen_bpms_process_variable.nextval from dual;
select gen_bpms_resource.nextval from dual;
select gen_bpms_xpdl.nextval from dual;
select gen_hist_activity_variable.nextval from dual;
select hibernate_sequence.nextval from dual;