-- Использовать для настройки ЭО, настройка в ручном режиме
--insert into app_setting (id, owner, setting_id, setting_name, setting_value, is_pass)
--values(hibernate_sequence.nextval, owner,'soap_ext_queue_host','Хост внешней электронной очереди', ip_or_host:port, 0);
