-----------------------------------------------------------
-- Скрипт на изменение структуры БД и перенос данных
-- для совместимости приложения для работы
-- с БД Firebird и Oracle
-----------------------------------------------------------


-- 1. Создание таблицы GOSSRVC_IN_OUT_DOCUMENT_JOURNL вместо GOSSRVC_IN_OUT_DOCUMENT_JOURNAL

CREATE TABLE GOSSRVC_IN_OUT_DOCUMENT_JOURNL (
    ID                  NUMERIC(18,0) NOT NULL,
    FROM_AGENT          VARCHAR(255),
    MESSENGER           VARCHAR(255),
    REGISTRATOR         VARCHAR(255),
    TO_AGENT            VARCHAR(255),
    DOC_PACKAGEITEM_ID  NUMERIC(18,0)
);

ALTER TABLE GOSSRVC_IN_OUT_DOCUMENT_JOURNL ADD PRIMARY KEY (ID);

ALTER TABLE GOSSRVC_IN_OUT_DOCUMENT_JOURNL ADD CONSTRAINT FK_GOSSRVC_IO_DOC_JOURNL_1 FOREIGN KEY (ID) REFERENCES SECURABLE (ID);
ALTER TABLE GOSSRVC_IN_OUT_DOCUMENT_JOURNL ADD CONSTRAINT FK_GOSSRVC_IO_DOC_JOURNL_2 FOREIGN KEY (DOC_PACKAGEITEM_ID) REFERENCES GOSSRVC_DOC_PACKAGE_ITEM (ID);

INSERT INTO GOSSRVC_IN_OUT_DOCUMENT_JOURNL SELECT * FROM GOSSRVC_IN_OUT_DOCUMENT_JOURNAL;

DROP TABLE GOSSRVC_IN_OUT_DOCUMENT_JOURNAL;

-- 2. Создание таблицы PORTAL_CONTENT_FILES_DEPEND вместо PORTAL_CONTENT_FILES_DEPENDENCE

CREATE TABLE PORTAL_CONTENT_FILES_DEPEND (
    ID                 NUMERIC(18,0) NOT NULL,
    PUID               VARCHAR(255),
    PORTAL_CONTENT_ID  NUMERIC(18,0)
);

ALTER TABLE PORTAL_CONTENT_FILES_DEPEND ADD PRIMARY KEY (ID);

ALTER TABLE PORTAL_CONTENT_FILES_DEPEND ADD CONSTRAINT FK_PORTAL_CF_DEPEND_1 FOREIGN KEY (PORTAL_CONTENT_ID) REFERENCES PORTAL_CONTENT (ID);

INSERT INTO PORTAL_CONTENT_FILES_DEPEND SELECT ID, UID, PORTAL_CONTENT_ID FROM PORTAL_CONTENT_FILES_DEPENDENCE;


DROP TABLE PORTAL_CONTENT_FILES_DEPENDENCE;



-- 3. Изменение названия поля COMMENT на CCOMMENT в таблице ARCHIVE_HISTORY

ALTER TABLE ARCHIVE_HISTORY ALTER COMMENT TO CCOMMENT;



-- 4. Изменение названия поля NUMBER на PNUMBER и TYPE на PTYPE в таблице PAYMENTORDER_HEAD

ALTER TABLE PAYMENTORDER_HEAD ALTER NUMBER TO PNUMBER;
ALTER TABLE PAYMENTORDER_HEAD ALTER TYPE TO PTYPE;



-- 5. Изменение названия поля TYPE на PTYPE и COMMENT на PCOMMENT в таблице PAYMENTORDER_SPEC

ALTER TABLE PAYMENTORDER_SPEC ALTER TYPE TO PTYPE;
ALTER TABLE PAYMENTORDER_SPEC ALTER COMMENT TO PCOMMENT;


-- 6. Изменение названия поля EXCLUSIVE на UEXCLUSIVE в таблице USER_DELEGATION

ALTER TABLE USER_DELEGATION ALTER EXCLUSIVE TO UEXCLUSIVE;


-- 7. Создание нового генератора для таблицы BPMS_ACTIVITY_VARIABLE_HIST

CREATE SEQUENCE G_BPMS_ACTIVITY_VARIABLE_HIST;
ALTER SEQUENCE G_BPMS_ACTIVITY_VARIABLE_HIST RESTART WITH 0;
SELECT GEN_ID(G_BPMS_ACTIVITY_VARIABLE_HIST, GEN_ID(GEN_BPMS_ACTIVITY_VARIABLE_HIST,1)) FROM RDB$DATABASE;

DROP SEQUENCE GEN_BPMS_ACTIVITY_VARIABLE_HIST;
