INSERT INTO CARD (CARD_CODE, CARD_NAME, GROUP_CODE, OWNER) VALUES ('SRegDoc', 'Нормативные документы', 'Услуги', NULL);
INSERT INTO CARD (CARD_CODE, CARD_NAME, GROUP_CODE, OWNER) VALUES ('SRelDocMFC', 'Нормативные документы МФЦ', 'Услуги', NULL);

INSERT INTO CARD_FIELD (FIELD_ID, FIELD_NAME, FIELD_TYPE, FIELD_VISIBLE, FIELD_CAPTION, FIELD_SIZE, FIELD_IDENT, CARD_CODE, FIELD_REQUIRED)
VALUES (hibernate_sequence.nextval, 'docAttach', 'attachment', 1, 'Приложение', 2048, NULL, 'SRegDoc', NULL);

INSERT INTO CARD_FIELD (FIELD_ID, FIELD_NAME, FIELD_TYPE, FIELD_VISIBLE, FIELD_CAPTION, FIELD_SIZE, FIELD_IDENT, CARD_CODE, FIELD_REQUIRED)
VALUES (hibernate_sequence.nextval, 'docAttach', 'attachment', 1, 'Приложение', 2048, NULL, 'SRelDocMFC', NULL);


INSERT INTO CARD_FIELD (FIELD_ID,FIELD_NAME,FIELD_TYPE,FIELD_VISIBLE,FIELD_CAPTION,FIELD_SIZE,FIELD_IDENT,CARD_CODE, FIELD_REQUIRED)
VALUES (hibernate_sequence.nextval,'docDesc','string',1,'Описание',2000,null,'SRegDoc', NULL);

INSERT INTO CARD_FIELD (FIELD_ID,FIELD_NAME,FIELD_TYPE,FIELD_VISIBLE,FIELD_CAPTION,FIELD_SIZE,FIELD_IDENT,CARD_CODE, FIELD_REQUIRED)
VALUES (hibernate_sequence.nextval,'docDesc','string',1,'Описание',2000,null,'SRelDocMFC', NULL);


