INSERT INTO CARD_FIELD (FIELD_ID, FIELD_NAME, FIELD_TYPE, FIELD_VISIBLE, FIELD_CAPTION, FIELD_SIZE, FIELD_IDENT, CARD_CODE, FIELD_REQUIRED)
VALUES (hibernate_sequence.nextval, 'serviceDoc', 'attachment', true, 'Приложение', 2048, NULL, 'SService', NULL);

