ALTER TABLE GOSSRVC_DOC_PACKAGE add PACK_DATE1 TIMESTAMP;

update GOSSRVC_DOC_PACKAGE
set PACK_DATE1 = PACK_DATE;

ALTER TABLE GOSSRVC_DOC_PACKAGE drop PACK_DATE;

alter table GOSSRVC_DOC_PACKAGE alter Pack_date1 to pack_date;