ALTER TABLE REQUEST add TRANSFER_DATE1 TIMESTAMP;

update REQUEST
set TRANSFER_DATE1 = TRANSFER_DATE;

ALTER TABLE REQUEST drop column TRANSFER_DATE;

alter table REQUEST rename column TRANSFER_DATE1 to TRANSFER_DATE;