update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = NULL
where (RDB$FIELD_NAME = 'DOC_TYPE') and
(RDB$RELATION_NAME = 'RELATIVE');

update RDB$RELATION_FIELDS set
RDB$NULL_FLAG = NULL
where (RDB$FIELD_NAME = 'TYPE_RELATION') and
(RDB$RELATION_NAME = 'RELATIVE');