--выполнить скрипт, запустить процедуру
SET TERM ^ ;

create or alter procedure "NORMALIZE_TABLE_FROM_SECURABLE"
as
declare variable P_SQL varchar(255);
declare variable TABLE_NAME varchar(255);
declare variable CONSTR_NAME varchar(255);
begin


  for   select F.RDB$CONSTRAINT_NAME as CONSTR_NAME, F.RDB$RELATION_NAME as table_NAME
        from RDB$REF_CONSTRAINTS C, RDB$RELATION_CONSTRAINTS F, RDB$RELATION_CONSTRAINTS T
        where C.RDB$CONSTRAINT_NAME = F.RDB$CONSTRAINT_NAME and
        T.RDB$CONSTRAINT_NAME = C.RDB$CONST_NAME_UQ and
        F.RDB$RELATION_NAME in ('PRINT_DOC_TYPE_TEMPLATE', 'GOSSRVC_OGV_DOC',
            'GOSSRVC_OGV_TEMPLATE', 'GOSSRVC_SERVICE_DOC', 'GOSSRVC_SERVICE_TEMPLATE',
            'SERVICE_INTEGRATION'
      )
      and
      T.RDB$RELATION_NAME = 'SECURABLE'
      into :CONSTR_NAME, :TABLE_NAME
  do
  begin
    P_SQL = 'ALTER TABLE '|| :TABLE_NAME || ' DROP CONSTRAINT ' || :CONSTR_NAME;
    EXECUTE STATEMENT :P_SQL;
  end


  for select rc.rdb$relation_name as table_NAME, rc.rdb$constraint_name as CONSTR_NAME
        from rdb$relation_constraints rc, rdb$index_segments rs
        where (rc.rdb$constraint_type = 'PRIMARY KEY') and
        (rs.rdb$index_name=rc.rdb$index_name)
        and   rc.rdb$relation_name in ('PRINT_DOC_TYPE_TEMPLATE', 'GOSSRVC_OGV_DOC',
            'GOSSRVC_OGV_TEMPLATE', 'GOSSRVC_SERVICE_TEMPLATE', 'SERVICE_INTEGRATION')
        into :TABLE_NAME, :CONSTR_NAME
  do
  begin
    P_SQL = 'ALTER TABLE '|| :TABLE_NAME || ' DROP CONSTRAINT ' || :CONSTR_NAME;
    EXECUTE STATEMENT :P_SQL;
  end

  update RDB$FIELDS set
        RDB$FIELD_TYPE = 16,
        RDB$FIELD_LENGTH = 8,
        RDB$CHARACTER_LENGTH = NULL,
        RDB$FIELD_SUB_TYPE = 1,
        RDB$FIELD_PRECISION = 18
        where RDB$FIELD_NAME =
        (select RDB$FIELD_SOURCE from RDB$RELATION_FIELDS where
        (RDB$RELATION_NAME = 'PRINT_DOC_TYPE_TEMPLATE') and (RDB$FIELD_NAME = 'ID'));

  update RDB$FIELDS set
        RDB$FIELD_TYPE = 16,
        RDB$FIELD_LENGTH = 8,
        RDB$CHARACTER_LENGTH = NULL,
        RDB$FIELD_SUB_TYPE = 1,
        RDB$FIELD_PRECISION = 18
        where RDB$FIELD_NAME =
        (select RDB$FIELD_SOURCE from RDB$RELATION_FIELDS where
        (RDB$RELATION_NAME = 'GOSSRVC_OGV_DOC') and (RDB$FIELD_NAME = 'ID'));

  update RDB$FIELDS set
        RDB$FIELD_TYPE = 16,
        RDB$FIELD_LENGTH = 8,
        RDB$CHARACTER_LENGTH = NULL,
        RDB$FIELD_SUB_TYPE = 1,
        RDB$FIELD_PRECISION = 18
        where RDB$FIELD_NAME =
        (select RDB$FIELD_SOURCE from RDB$RELATION_FIELDS where
        (RDB$RELATION_NAME = 'GOSSRVC_OGV_TEMPLATE') and (RDB$FIELD_NAME = 'ID'));

  update RDB$FIELDS set
        RDB$FIELD_TYPE = 16,
        RDB$FIELD_LENGTH = 8,
        RDB$CHARACTER_LENGTH = NULL,
        RDB$FIELD_SUB_TYPE = 1,
        RDB$FIELD_PRECISION = 18
        where RDB$FIELD_NAME =
        (select RDB$FIELD_SOURCE from RDB$RELATION_FIELDS where
        (RDB$RELATION_NAME = 'GOSSRVC_SERVICE_TEMPLATE') and (RDB$FIELD_NAME = 'ID'));

  update RDB$FIELDS set
        RDB$FIELD_TYPE = 16,
        RDB$FIELD_LENGTH = 8,
        RDB$CHARACTER_LENGTH = NULL,
        RDB$FIELD_SUB_TYPE = 1,
        RDB$FIELD_PRECISION = 18
        where RDB$FIELD_NAME =
        (select RDB$FIELD_SOURCE from RDB$RELATION_FIELDS where
        (RDB$RELATION_NAME = 'SERVICE_INTEGRATION') and (RDB$FIELD_NAME = 'ID'));


   P_SQL = 'ALTER TABLE PRINT_DOC_TYPE_TEMPLATE ADD PRIMARY KEY (ID)';
   EXECUTE STATEMENT :P_SQL;

   P_SQL = 'ALTER TABLE GOSSRVC_OGV_DOC ADD PRIMARY KEY (ID)';
   EXECUTE STATEMENT :P_SQL;


   P_SQL = 'ALTER TABLE GOSSRVC_OGV_TEMPLATE ADD PRIMARY KEY (ID)';
   EXECUTE STATEMENT :P_SQL;

   P_SQL = 'ALTER TABLE GOSSRVC_SERVICE_TEMPLATE ADD PRIMARY KEY (ID)';
   EXECUTE STATEMENT :P_SQL;

   P_SQL = 'ALTER TABLE SERVICE_INTEGRATION ADD PRIMARY KEY (ID)';
   EXECUTE STATEMENT :P_SQL;

   P_SQL =  'ALTER TABLE PRINT_DOC_TYPE_TEMPLATE ADD CONSTRAINT SEC_101 FOREIGN KEY (ID) REFERENCES SECURABLE (ID)';
   EXECUTE STATEMENT :P_SQL;

   P_SQL =  'ALTER TABLE GOSSRVC_OGV_DOC ADD CONSTRAINT SEC_102 FOREIGN KEY (ID) REFERENCES SECURABLE (ID)';
   EXECUTE STATEMENT :P_SQL;

      P_SQL =  'ALTER TABLE GOSSRVC_OGV_TEMPLATE ADD CONSTRAINT SEC_103 FOREIGN KEY (ID) REFERENCES SECURABLE (ID)';
   EXECUTE STATEMENT :P_SQL;

      P_SQL =  'ALTER TABLE GOSSRVC_SERVICE_TEMPLATE ADD CONSTRAINT SEC_104 FOREIGN KEY (ID) REFERENCES SECURABLE (ID)';
   EXECUTE STATEMENT :P_SQL;

      P_SQL =  'ALTER TABLE GOSSRVC_OGV_DOC ADD CONSTRAINT SEC_105 FOREIGN KEY (ID) REFERENCES SECURABLE (ID)';
   EXECUTE STATEMENT :P_SQL;


  for select F.RDB$CONSTRAINT_NAME as CONSTR_NAME, F.RDB$RELATION_NAME as table_NAME
        from RDB$REF_CONSTRAINTS C, RDB$RELATION_CONSTRAINTS F, RDB$RELATION_CONSTRAINTS T
        where C.RDB$CONSTRAINT_NAME = F.RDB$CONSTRAINT_NAME and
        T.RDB$CONSTRAINT_NAME = C.RDB$CONST_NAME_UQ and
        F.RDB$RELATION_NAME in ('GOSSRVC_OGV_DOC')
      and
      T.RDB$RELATION_NAME = 'GOSSRVC_SERVICE_DOC'
      into :CONSTR_NAME, :TABLE_NAME
  do
  begin
    P_SQL = 'ALTER TABLE '|| :TABLE_NAME || ' DROP CONSTRAINT ' || :CONSTR_NAME;
    EXECUTE STATEMENT :P_SQL;
  end



  for select rc.rdb$relation_name as table_NAME, rc.rdb$constraint_name as CONSTR_NAME
        from rdb$relation_constraints rc, rdb$index_segments rs
        where (rc.rdb$constraint_type = 'PRIMARY KEY') and
        (rs.rdb$index_name=rc.rdb$index_name)
        and   rc.rdb$relation_name in ('GOSSRVC_SERVICE_DOC')
        into :TABLE_NAME, :CONSTR_NAME
  do
  begin
    P_SQL = 'ALTER TABLE '|| :TABLE_NAME || ' DROP CONSTRAINT ' || :CONSTR_NAME;
    EXECUTE STATEMENT :P_SQL;
  end

  update RDB$FIELDS set
        RDB$FIELD_TYPE = 16,
        RDB$FIELD_LENGTH = 8,
        RDB$CHARACTER_LENGTH = NULL,
        RDB$FIELD_SUB_TYPE = 1,
        RDB$FIELD_PRECISION = 18
        where RDB$FIELD_NAME =
        (select RDB$FIELD_SOURCE from RDB$RELATION_FIELDS where
        (RDB$RELATION_NAME = 'GOSSRVC_SERVICE_DOC') and (RDB$FIELD_NAME = 'ID'));

  update RDB$FIELDS set
        RDB$FIELD_TYPE = 16,
        RDB$FIELD_LENGTH = 8,
        RDB$CHARACTER_LENGTH = NULL,
        RDB$FIELD_SUB_TYPE = 1,
        RDB$FIELD_PRECISION = 18
        where RDB$FIELD_NAME =
        (select RDB$FIELD_SOURCE from RDB$RELATION_FIELDS where
        (RDB$RELATION_NAME = 'GOSSRVC_OGV_DOC') and (RDB$FIELD_NAME = 'SERVICE_DOC_ID'));



   P_SQL = 'ALTER TABLE GOSSRVC_SERVICE_DOC ADD PRIMARY KEY (ID)';
   EXECUTE STATEMENT :P_SQL;


      P_SQL =  'ALTER TABLE GOSSRVC_OGV_DOC ADD CONSTRAINT FKGOSSRVC_S_D_101 FOREIGN KEY (SERVICE_DOC_ID) REFERENCES GOSSRVC_SERVICE_DOC (ID)';
   EXECUTE STATEMENT :P_SQL;

      P_SQL =  'ALTER TABLE GOSSRVC_SERVICE_DOC ADD CONSTRAINT SEC_106 FOREIGN KEY (ID) REFERENCES SECURABLE (ID)';
   EXECUTE STATEMENT :P_SQL;
   EXIT;
end^

SET TERM ; ^

GRANT EXECUTE ON PROCEDURE "NORMALIZE_TABLE_FROM_SECURABLE" TO SYSDBA;