ALTER TABLE REQUEST add TRANSFER_DATE1 TIMESTAMP;

update REQUEST
set TRANSFER_DATE1 = TRANSFER_DATE;

ALTER TABLE REQUEST drop TRANSFER_DATE;

alter table REQUEST alter TRANSFER_DATE1 to TRANSFER_DATE;