drop table GOSSRVC_OGV_RESULT;
drop table GOSSRVC_OGV_SERVICE;
drop table GOSSRVC_REJECT;
drop table GOSSRVC_RESULT;
drop table GOSSRVC_SERVICE_REJECT_TEMPLATE;
drop table GOSSRVC_SERVICE_RESULT;
drop table GOSSRVC_SERVICE_RESULT_TEMPLATE;
ALTER TABLE OBJECT_GROUP DROP MAINSERVICEID2;
ALTER TABLE Gossrvc_Ogv_Doc DROP RESULT_DOC_TYPE_ID;
ALTER TABLE Gossrvc_Ogv_Doc DROP RESULT_DOC_CLASS_ID;

