ALTER TABLE CONTRACTOR MODIFY name varchar2(1024);
ALTER TABLE CONTRACTOR_DOC MODIFY name varchar2(1024);
ALTER TABLE CONTRACTOR_AUD MODIFY name varchar2(1024);
ALTER TABLE CONTRACTOR_DOC_AUD MODIFY name varchar2(1024);