INSERT INTO CARD_FIELD
		(FIELD_ID,FIELD_NAME,FIELD_TYPE,FIELD_VISIBLE,FIELD_CAPTION,FIELD_SIZE,FIELD_IDENT,CARD_CODE,FIELD_REQUIRED,FIELD_MAX_VALUE,FIELD_MIN_VALUE,VALIDATOR_ID,FIELD_READONLY)
VALUES 	(nextval('hibernate_sequence'),'addressOGV','string',true,'Адрес ОГВ',200,null,'SGosOrg',false,null,null,'',false);